CREATE TABLE author (	id INTEGER NOT NULL,	name VARCHAR(60),	PRIMARY KEY (id),	UNIQUE (name))
CREATE TABLE book (	id INTEGER NOT NULL,	title VARCHAR(120),	PRIMARY KEY (id))
CREATE TABLE user (	id INTEGER NOT NULL,	nickname VARCHAR(64),	email VARCHAR(120),	role SMALLINT,	PRIMARY KEY (id),	UNIQUE (nickname),	UNIQUE (email))
CREATE TABLE books (	author_id INTEGER,	book_id INTEGER,	FOREIGN KEY(author_id) REFERENCES author (id),	FOREIGN KEY(book_id) REFERENCES book (id))
INSERT INTO author (name) VALUES ('Pushkin Alexander')
INSERT INTO author (name) VALUES ('George Byron')
INSERT INTO author (name) VALUES ('Charles Dickens')
INSERT INTO author (name) VALUES ('Darya Doncova')
INSERT INTO book (title) VALUES ('Harry Potter')
INSERT INTO book (title) VALUES ('Anna Karenina')
INSERT INTO book (title) VALUES ('Illya Muromets')
INSERT INTO book (title) VALUES ('Mockingbird')
INSERT INTO books (author_id, book_id) VALUES (1, 1)
INSERT INTO books (author_id, book_id) VALUES (1, 2)
INSERT INTO books (author_id, book_id) VALUES (2, 2)
INSERT INTO books (author_id, book_id) VALUES (4, 4)
INSERT INTO books (author_id, book_id) VALUES (3, 1)
INSERT INTO books (author_id, book_id) VALUES (3, 3)